apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-poi
  namespace: api-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
        - name: poi
          image: registrynhj5026.azurecr.io/tripinsights/poi:1.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "500m"
          ports:
            - containerPort: 80
              name: http
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
            - name: SQL_SERVER
              value: sqlservernhj5026.database.windows.net
            - name: SQL_USER
              value: sqladminnHj5026
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: SQL_PASSWORD # the application expects to find the SQL connection password in this environment variable
              valueFrom:
                secretKeyRef:
                  name: mssql # the name of the Kubernetes secret containing the data
                  key: password # the key inside the Kubernetes secret containing the data
          livenessProbe:
            httpGet:
              path: /api/poi/healthcheck
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
