apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-poi
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      - name: poi
        image: registrynhj5026.azurecr.io/tripinsights/poi:1.0
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: secrets-store-inline
          mountPath: "/secrets"
          readOnly: true
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Production
          - name: SQL_SERVER
            value: sqlservernhj5026.database.windows.net
          - name: SQL_USER
            value: sqladminnHj5026
          - name: SQL_DBNAME
            value: mydrivingDB
        livenessProbe:
          httpGet:
            path: /api/poi/healthcheck
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 15     
      volumes:
      - name: secrets-store-inline
        csi:
          driver: secrets-store.csi.k8s.io
          readOnly: true
          volumeAttributes:
            secretProviderClass: aks-openhack-kv
---
apiVersion: v1
kind: Service
metadata:
  name: poi-service
  namespace: api
spec:
  selector:
    app: poi
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80