apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripinsights-userjava
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: userjava
  template:
    metadata:
      labels:
        app: userjava
    spec:
      containers:
        - name: userjava
          image: registrynhj5026.azurecr.io/tripinsights/user-java:1.0
          resources:
            requests:
              memory: "1Gi"
              cpu: "1000m"
            limits:
              memory: "1Gi"
              cpu: "1000m"
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SQL_SERVER
              value: sqlservernhj5026.database.windows.net
            - name: SQL_USER
              value: sqladminnHj5026
            - name: SQL_DBNAME
              value: mydrivingDB
            - name: SQL_PASSWORD # the application expects to find the SQL connection password in this environment variable
              valueFrom:
                secretKeyRef:
                  name: mssql # the name of the Kubernetes secret containing the data
                  key: password # the key inside the Kubernetes secret containing the data
          livenessProbe:
            httpGet:
              path: /api/user-java/healthcheck
              port: 80
            initialDelaySeconds: 60
            periodSeconds: 15
---
apiVersion: v1
kind: Service
metadata:
  name: userjava-service
  namespace: api
spec:
  selector:
    app: userjava
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
